Repository part4-team6/Pickly, pull requests merged in 2025-06, with the labels that each got.

#28 [Feat/smj/input component] Input 필드 통합 및 EyeToggle 처리 개선
  package-lock.json
  package.json
  public/icons/eye_close.svg
  public/icons/eye_open.svg
  src/app/globals.css
  src/app/signin/page.tsx
  src/app/signin/validationSchema.ts
  src/app/signup/page.tsx
  src/app/signup/validationSchema.ts
  src/app/test/input/page.tsx
  src/components/input/InputField.tsx
  src/components/input/Textbox.tsx
Labels: refactor, feature

#36 [Feat/ksy/product id api] - 상세페이지 로딩시 ssr로 전부 연결 확인
  src/app/product/[id]/page.tsx
  src/components/CategoryChip.tsx
  src/components/input/InputField.tsx
  src/components/input/Textbox.tsx
  src/components/shared/SortDropDown.tsx
  src/features/productId/api.ts
  src/features/productId/components/ProductIdDetail/ProductIdDetail.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetailButton.tsx
  src/features/productId/components/ProductIdStats/ProductIdStats.tsx
  src/features/productId/components/ProductIdStats/ProductIdStatsBone.tsx
  src/features/productId/components/ProductReviews/ProductReviewClient.tsx
  src/features/productId/components/ProductReviews/ProductReviewsFetch.tsx
  src/features/productId/components/ProductReviews/ProductReviewsInfinite.tsx
  src/features/productId/components/modal/ProductReviewModal/ProductIdGetModal.tsx
  src/features/productId/components/modal/ProductReviewModal/ProductReviewInputModal.tsx
  src/features/productId/hooks/useGetProductSort.ts
  src/features/productId/hooks/useGetProductsIdReview.ts
  src/features/productId/types.ts
Labels: refactor

#45 [Refactor/smj/input textbox] InputField, Textbox 컨포넌트 리팩토링
  .vscode/settings.json
  package-lock.json
  public/icons/login_sns_google.svg
  public/icons/login_sns_kakao.svg
  src/app/globals.css
  src/app/signin/validationSchema.ts
  src/app/signup/validationSchema.ts
  src/app/test/input/page.tsx
  src/components/input/InputField.tsx
  src/components/input/Textbox.tsx
  src/lib/axios/index.ts
Labels: ♻️ refactor

#38 Feat/hsw/add product modal
  public/icons/addImage.png
  src/app/globals.css
  src/app/homepage/[id]/page.tsx
  src/app/homepage/page.tsx
  src/app/page.tsx
  src/components/input/InputField.tsx
  src/components/input/Textbox.tsx
  src/components/shared/AddEditProductModal.tsx
  src/components/shared/CategoryDropDown.tsx
  src/components/shared/FloatingButton.tsx
  src/components/shared/Header.tsx
  src/components/shared/SearchPage.tsx
  src/features/home/components/CategoryTab.tsx
  src/features/home/components/MoreProducts.tsx
  src/features/home/components/SortComponent.tsx
  src/features/modals/store/modalStore.ts
Labels: 🐞 bug, ✨ feature, 🖌️ publishing

#42 [Feat/key/product api post] - 리뷰 좋아요, 찜, 리뷰작성과 동시에 통계도 실시간 적용 등
  src/components/shared/ThumbsUpButton.tsx
  src/components/shared/TypeButton.tsx
  src/features/productId/api.ts
  src/features/productId/components/ProductIdDetail/ProductIdDetail.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetailHeart.tsx
  src/features/productId/components/ProductIdStats/ProductIdStats.tsx
  src/features/productId/components/ProductIdStats/ProductIdStatsClient.tsx
  src/features/productId/components/ProductReviews/ProductReviewsFetch.tsx
  src/features/productId/components/ProductReviews/ProductReviewsInfinite.tsx
  src/features/productId/components/ProductReviews/ProductReviewsListComponent.tsx
  src/features/productId/components/modal/ProductReviewModal/ProductReviewInputModal.tsx
  src/features/productId/components/modal/ProductReviewModal/ProductReviewModal.tsx
  src/features/productId/hooks/useGetProductsIdReviews.ts
  src/features/productId/hooks/useLikeButton.ts
  src/features/productId/libs/useProductStatsStore.ts
  src/features/productId/types.ts
Labels: ♻️ refactor, ✨ feature

#56 [Fix/ksy/local category] - 모달 쿼리스트링으로 관리 + 카테고리 별로 비교하기 목록 관리
  src/app/product/[id]/page.tsx
  src/components/shared/SortDropDown.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetail.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetailButton.tsx
  src/features/productId/components/ProductIdStats/ProductIdStats.tsx
  src/features/productId/components/ProductReviews/ProductReviewClient.tsx
  src/features/productId/components/modal/ProductCompareModal/ProductCompareChangeModal.tsx
  src/features/productId/components/modal/ProductCompareModal/ProductCompareModal.tsx
  src/features/productId/components/modal/ProductCompareModal/ProductComparePlusModal.tsx
  src/features/productId/hooks/useGetUser.ts
  src/features/productId/libs/useUserStore.ts
Labels: ♻️ refactor

#59 Feat/hsw/header state change
  src/app/api/cookie/route.ts
  src/components/shared/Header.tsx
  src/features/header/hooks/useAuthentication.ts
  test/test.http
Labels: ✨ feature

#61 Feat/hsw/modal api
  package-lock.json
  package.json
  src/app/homepage/[id]/page.tsx
  src/app/homepage/page.tsx
  src/components/input/InputField.tsx
  src/components/shared/AddEditProductModal.tsx
  src/components/shared/CategoryDropDown.tsx
  src/components/shared/Header.tsx
  src/components/shared/SearchPage.tsx
  src/features/header/hooks/useAuthentication.ts
  src/features/header/hooks/useBlockScroll.ts
  src/features/header/hooks/useResize.ts
  src/features/home/components/Category.tsx
  src/features/home/components/CategoryTab.tsx
  src/features/home/components/HighStarProduct.tsx
  src/features/home/components/MoreProducts.tsx
  src/features/home/modals/store/modalStore.ts
  src/features/home/services/postProduct.ts
Labels: ♻️ refactor, ✨ feature

#66 feat: 404 페이지 구현
  public/icons/404logo.png
  public/icons/tear.png
  src/app/not-found.tsx
  src/components/shared/Header.tsx
  src/features/header/hooks/useBlockScroll.ts
Labels: ✨ feature, 🖌️ publishing

#71 [Feat/smj/login signup page] 로그인/회원가입 시 accessToken 쿠키로 저장 로직 구현
  .vscode/settings.json
  package-lock.json
  src/app/signin/page.tsx
  src/app/signin/useSignIn.ts
  src/app/signin/validationSchema.ts
  src/app/signup/page.tsx
  src/app/signup/useSignUp.ts
  src/app/signup/validationSchema.ts
  src/components/input/InputField.tsx
  src/components/input/Textbox.tsx
  src/components/shared/BaseButton.tsx
  src/components/shared/NoticeModal.tsx
Labels: ✨ feature

#72 [Fix/ksy/product id cookie] 각종 오류 수정 + 비교하기 기능 게스트 모드 적용
  src/app/product/[id]/page.tsx
  src/app/test/page.tsx
  src/components/input/Textbox.tsx
  src/components/shared/BaseButton.tsx
  src/components/shared/ProductComparePlusModal.tsx
  src/components/shared/SigninModal.tsx
  src/components/shared/SortDropDown.tsx
  src/components/shared/ThumbsUpButton.tsx
  src/features/productId/api.ts
  src/features/productId/axiosInstance.ts
  src/features/productId/components/ProductIdDetail/ProductIdDetailButton.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetailHeart.tsx
  src/features/productId/components/ProductIdStats/ProductIdStatsClient.tsx
  src/features/productId/components/ProductReviews/ProductReviewClient.tsx
  src/features/productId/components/ProductReviews/ProductReviewDelete.tsx
  src/features/productId/components/ProductReviews/ProductReviewSort.tsx
  src/features/productId/components/ProductReviews/ProductReviewsFetch.tsx
  src/features/productId/components/ProductReviews/ProductReviewsInfinite.tsx
  src/features/productId/components/ProductReviews/ProductReviewsListComponent.tsx
  src/features/productId/components/modal/ProductCompareModal/ProductCompareModal.tsx
  src/features/productId/hooks/useGetUser.ts
  src/features/productId/hooks/useLikeButton.ts
  src/features/productId/libs/axiosInstance.ts
  src/features/productId/libs/useUserStore.ts
  src/lib/utils/triggerShowSigninModal.ts
Labels: ✨ feature, 🛠️ fix

#77 [feat/smj/login-signup-page] style: 로그인/회원가입 페이지 UI 개선
  .vscode/settings.json
  package-lock.json
  package.json
  public/signup_bg.jpg
  public/signup_logo.svg
  public/sns_gg_bg.png
  src/app/globals.css
  src/app/layout.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/app/signup/useSignUp.ts
  src/components/input/Textbox.tsx
  src/components/shared/NoticeModal.tsx
Labels: style

#73 Feat/hsw/product modals
  src/app/api/login/route.ts
  src/app/homepage/[id]/page.tsx
  src/app/homepage/page.tsx
  src/app/signup/page.tsx
  src/components/input/Textbox.tsx
  src/components/shared/AddEditProductModal.tsx
  src/components/shared/FloatingButton.tsx
  src/components/shared/ProductCard.tsx
  src/components/shared/ProductComparePlusModal.tsx
  src/features/header/hooks/useAuthentication.ts
  src/features/home/services/postProduct.ts
  src/features/home/types/productType.ts
  src/lib/utils/addProductFunction.ts
  src/lib/utils/editProductFunction.ts
Labels: 🐞 bug, ♻️ refactor, ✨ feature, style

#82 [Feat/ksy/spotify youtube api] - 유튜브 api, 스포티파이 api, openAi api + 추가 반응형 + 리뷰 없을 때 문구 추가
  package-lock.json
  package.json
  src/app/api/openai/route.ts
  src/app/api/spotify-token/route.ts
  src/app/api/youtube-search/route.ts
  src/app/product/[id]/page.tsx
  src/features/productId/components/ProductApi/ProductApiClient.tsx
  src/features/productId/components/ProductApi/ProductApiDetail.tsx
  src/features/productId/components/ProductApi/ProductSpotifyClient.tsx
  src/features/productId/components/ProductApi/ProductYouTubeSection.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetail.tsx
  src/features/productId/components/ProductReviews/ProductReviewSort.tsx
  src/features/productId/components/ProductReviews/ProductReviewsFetch.tsx
  src/features/productId/hooks/fetchArtistAlbum.ts
  src/features/productId/hooks/getSpotify.ts
  src/features/productId/hooks/useGetMusicvideo.ts
  src/features/productId/youtube-video.ts
Labels: ✨ feature

#86 Feat/hsw/landing page
  package-lock.json
  package.json
  public/images/addProductModalImage.png
  public/images/clothes:accessories.png
  public/images/compareProduct.png
  public/images/compareProductMobile.png
  public/images/electronicdevices.png
  public/images/furniture:interior.png
  public/images/homepageDesktop.png
  public/images/homepageMobile.png
  public/images/homepageTablet.png
  public/images/hongseungwon.jpeg
  public/images/hotel.png
  public/images/lecture:book.png
  public/images/makeups.png
  public/images/movie:drama.png
  public/images/music.png
  public/images/restaurant.png
  public/images/reviewModalImage.png
  public/images/sometimesTie.png
  public/images/sometimesTieMobile.png
  public/images/sometimesWin.png
  public/images/sometimesWinMobile.png
  public/images/미진님프사.jpeg
  public/images/수연님프사.jpeg
  public/images/하은님프사.jpeg
  public/images/혁진님프사.jpeg
  src/app/landingpage/page.tsx
  src/app/page.tsx
  src/components/shared/BaseButton.tsx
  src/components/shared/ProductCard.tsx
  src/features/landing/components/AddProductModalIntro.tsx
  src/features/landing/components/AddReviewModalIntro.tsx
  src/features/landing/components/CategoryCard.tsx
  src/features/landing/components/CategoryGrid.tsx
  src/features/landing/components/CompareProducts.tsx
  src/features/landing/components/Footer.tsx
  src/features/landing/components/HomePagePreview.tsx
  src/features/landing/components/LandingPageTop.tsx
  src/features/landing/components/MovingCategories.tsx
  src/features/landing/components/SometimesTie.tsx
  src/features/landing/components/SometimesWin.tsx
Labels: ✨ feature, 🖌️ publishing

#89 fix: 파일명 수정
  public/images/clothesaccessories.png
  public/images/furnitureinterior.png
  public/images/lecturebook.png
  public/images/moviedrama.png
  src/app/landingpage/page.tsx
  src/components/input/Textbox.tsx
  src/components/shared/BaseButton.tsx
  src/features/landing/components/CategoryGrid.tsx
  src/features/landing/components/LandingPageTop.tsx
  src/features/landing/components/MovingCategories.tsx
Labels: 🐞 bug

#98 [Fix/ksy/product id all] - 카테고리(영화/드라마, 호텔, 식당) 구글지도와 유튜브 연결 + 카톡 공유기능
  next.config.ts
  package-lock.json
  package.json
  src/app/api/openai/extract-movie/route.ts
  src/app/api/openai/extract-music/route.ts
  src/app/api/openai/extract-place/route.ts
  src/app/api/openai/route.ts
  src/app/api/youtube-search/route.ts
  src/app/layout.tsx
  src/app/product/[id]/page.tsx
  src/features/productId/components/ProductApi/MapView.tsx
  src/features/productId/components/ProductApi/ProductApiClient.tsx
  src/features/productId/components/ProductApi/ProductApiDetail.tsx
  src/features/productId/components/ProductApi/ProductSpotifyClient.tsx
  src/features/productId/components/ProductApi/ProductYouTubeSection.tsx
  src/features/productId/components/ProductApi/ProductYouTubeWrapper.tsx
  src/features/productId/components/ProductIdDetail/CopyLinkImage.tsx
  src/features/productId/components/ProductIdDetail/LazyLoadSection.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetail.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetailButton.tsx
  src/features/productId/components/ProductImage.tsx
  src/features/productId/components/ProductReviews/ProductReviewEdit.tsx
  src/features/productId/components/ProductReviews/ProductReviewsFetch.tsx
  src/features/productId/components/ProductReviews/ProductReviewsListComponent.tsx
  src/features/productId/components/modal/ProductCompareModal/ProductCompareModal.tsx
  src/features/productId/components/modal/ProductReviewModal/ProductIdGetModal.tsx
  src/features/productId/components/modal/ProductReviewModal/ProductReviewInputModal.tsx
  src/features/productId/components/modal/ProductReviewModal/ProductReviewModal.tsx
  src/features/productId/hooks/fetchArtistAlbum.ts
  src/features/productId/hooks/fetchOpenAi.ts
  src/features/productId/hooks/useGetProductId.ts
  src/types/global.d.ts
  tsconfig.json
Labels: ✨ feature

#102 Bug/hsw/solve bug2
  public/icons/cancel.png
  public/robots.txt
  public/vercel.svg
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/mypage/loading.tsx
  src/app/users/[id]/loading.tsx
  src/components/input/Textbox.tsx
  src/components/shared/AddEditProductModal.tsx
  src/components/shared/Header.tsx
  src/features/Profile/api/getUserProducts.ts
  src/features/home/components/ReviewerTab.tsx
  src/features/home/modals/store/modalStore.ts
  src/features/productId/components/ProductReviews/ProductReviewsListComponent.tsx
  src/lib/utils/addProductFunction.ts
  src/lib/utils/editProductFunction.ts
Labels: 🐞 bug, ✨ feature

#120 [feat/ksy/deleteProduct] - 상품삭제 기능 추가 + 맵에 해당 위치가 없을 때 문구 추가
  public/icons/trash-icon.png
  src/components/shared/ProductComparePlusModal.tsx
  src/features/productId/api.ts
  src/features/productId/components/ProductApi/MapView.tsx
  src/features/productId/components/ProductApi/ProductApiDetail.tsx
  src/features/productId/components/ProductIdDetail/CopyLinkImage.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetail.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetailButton.tsx
Labels: ✨ feature

#122 Bug/hsw/solve bug5
  src/app/homepage/[id]/page.tsx
  src/app/homepage/page.tsx
  src/app/landingpage/page.tsx
  src/app/layout.tsx
  src/app/mypage/page.tsx
  src/components/shared/AddEditProductModal.tsx
  src/components/shared/CategoryDropDown.tsx
  src/components/shared/FloatingButton.tsx
  src/components/shared/Header.tsx
  src/components/shared/ProductCard.tsx
  src/features/Profile/components/ProductGrid.tsx
  src/features/home/components/Category.tsx
  src/features/home/components/CategoryTab.tsx
  src/features/home/components/HighStarProduct.tsx
  src/features/home/components/MoreProducts.tsx
  src/features/home/components/ReviewerRanking.tsx
  src/features/home/components/ReviewerTab.tsx
  src/features/home/modals/store/modalStore.ts
  src/features/landing/components/AddProductModalIntro.tsx
  src/features/landing/components/AddReviewModalIntro.tsx
  src/features/landing/components/CategoryCard.tsx
  src/features/landing/components/CategoryGrid.tsx
  src/features/landing/components/CompareProducts.tsx
  src/features/landing/components/Footer.tsx
  src/features/landing/components/HomePagePreview.tsx
  src/features/landing/components/LandingPageTop.tsx
  src/features/landing/components/MovingCategories.tsx
  src/features/landing/components/SometimesTie.tsx
Labels: 🐞 bug, ♻️ refactor, style, 🚀 enhancement

#117 [Fix/smj/login] 로그인 회원가입 관련 사용하지 않는 내용 삭제
  src/app/auth/google/callback/page.tsx
  src/app/auth/kakao/callback/page.tsx
  src/app/signin/error.tsx
  src/app/signup/[provider]/page.tsx
  src/features/google/components/GoogleCallback.tsx
  src/features/signin/components/SigninPage.tsx
  src/features/signup/components/SignUpPage.tsx
Labels: ♻️ refactor

#124 enhancement: 랜딩 페이지 모바일 그리드 개선
  public/images/app.jpg
  src/features/landing/components/CategoryCard.tsx
  src/features/landing/components/CategoryGrid.tsx
Labels: 🐞 bug, 🚀 enhancement

#125 [fix/ksy/pngAndQuery] - 상품수정및 아이콘 깨지는거 수정
  public/icons/kakako-link.png
  public/icons/link-share.png
  public/icons/trash-icon.png
  public/images/kakao-link.png
  public/images/link-share.png
  src/app/homepage/page.tsx
  src/components/shared/AddEditProductModal.tsx
  src/features/productId/components/ProductIdDetail/CopyLinkImage.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetail.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetailButton.tsx
  src/features/productId/components/ProductReviews/ProductReviewEdit.tsx
  src/lib/utils/addProductFunction.ts
  src/lib/utils/editProductFunction.ts
Labels: ♻️ refactor, 🛠️ fix

#127 [Fix/ksy/modal2] - 로딩 두번이랑 모달 오류 해결
  src/app/product/[id]/page.tsx
  src/components/shared/AddEditProductModal.tsx
  src/features/productId/components/ProductApi/LoadingSkeletonYoutube.tsx
  src/features/productId/components/ProductApi/ProductApiClient.tsx
  src/features/productId/components/ProductApi/ProductApiDetail.tsx
  src/features/productId/components/ProductApi/ProductYouTubeSection.tsx
  src/features/productId/components/ProductApi/ProductYouTubeWrapper.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetailServer.tsx
  src/features/productId/components/ProductIdStats/ProductIdStats.tsx
  src/features/productId/hooks/useGetMusicvideo.ts
  src/features/productId/libs/getOpenAi.ts
Labels: 🛠️ fix

#128 fix: 코드 정리
  src/app/homepage/[id]/page.tsx
  src/app/homepage/page.tsx
Labels: ♻️ refactor

#130 [fix/ksy/api3] - 상세페이지 전체 꺼지는 문제 해결
  src/components/shared/AddEditProductModal.tsx
  src/features/productId/components/ProductApi/MapView.tsx
  src/features/productId/components/ProductApi/ProductApiDetail.tsx
  src/features/productId/components/ProductApi/ProductYouTubeSection.tsx
Labels: 🛠️ fix

#131 [refactor/ksy/api]상품 수정 및 카테고리 분리
  next.config.ts
  src/app/product/[id]/page.tsx
  src/features/productId/components/ProductApi/ProductApiDetail.tsx
  src/features/productId/components/ProductApi/ProductSpotifyClient.tsx
  src/features/productId/components/ProductIdStats/ProductIdStatsClient.tsx
  src/features/productId/components/ProductReviews/ProductReviewDelete.tsx
  src/features/productId/components/ProductReviews/ProductReviewEdit.tsx
  src/features/productId/components/ProductReviews/ProductReviewEditDelete.tsx
  src/features/productId/components/ProductReviews/ProductReviewSort.tsx
  src/features/productId/components/ProductReviews/ProductReviewsFetch.tsx
  src/features/productId/components/ProductReviews/ProductReviewsInfinite.tsx
  src/features/productId/components/ProductReviews/ProductReviewsListComponent.tsx
  src/features/productId/components/modal/ProductReviewModal/ProductReviewInputModal.tsx
  src/features/productId/components/modal/ProductReviewModal/ProductReviewModal.tsx
  src/features/productId/components/modal/ProductReviewModal/TextboxReview.tsx
Labels: ♻️ refactor, 🛠️ fix

#132 Bug/hsw/solve bug7
  package-lock.json
  package.json
  src/app/homepage/[id]/page.tsx
  src/app/landingpage/page.tsx
  src/features/landing/components/MovingCategories.tsx
Labels: 🚀 enhancement

#138 [fix/ksy/likebutton] - 리뷰 좋아요 상품 좋아요 새로고침해도 반영
  src/components/shared/ThumbsUpButton.tsx
  src/features/productId/api.ts
  src/features/productId/components/ProductIdDetail/ProductIdDetail.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetailHeart.tsx
  src/features/productId/components/ProductReviews/ProductReviewsInfinite.tsx
  src/features/productId/components/ProductReviews/ProductReviewsListComponent.tsx
  src/features/productId/hooks/useLikeButton.ts
Labels: 🛠️ fix

#139 [fix/ksy/productStat] - 각 상품 id 스탯을 상품별 zustand 따로 만들어서 관리 + 로그아웃시 유저데이터 삭제
  src/app/api/openai/extract-place/route.ts
  src/app/compare/page.tsx
  src/components/shared/TypeButton.tsx
  src/features/Profile/components/LogoutButton.tsx
  src/features/compare/components/CompareClient.tsx
  src/features/home/services/getProduct.ts
  src/features/home/services/postProduct.ts
  src/features/productId/axiosInstance.ts
  src/features/productId/components/ProductApi/MapView.tsx
  src/features/productId/components/ProductIdDetail/CopyLinkImage.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetailHeart.tsx
  src/features/productId/components/ProductIdStats/ProductIdStatsClient.tsx
  src/features/productId/components/ProductReviews/ProductReviewDelete.tsx
  src/features/productId/components/ProductReviews/ProductReviewEdit.tsx
  src/features/productId/components/modal/ProductReviewModal/ProductReviewModal.tsx
  src/features/productId/hooks/fetchOpenAi.ts
  src/features/productId/libs/useProductStatsStore.ts
  src/features/signup/components/OAuthSignUpPage.tsx
  src/lib/utils/addProductFunction.ts
Labels: 🐞 bug, 🛠️ fix

#142 [feat/ksy/mongo2] - 몽고추가
  package-lock.json
  package.json
  src/app/api/youtube-search/route.ts
  src/features/productId/components/ProductApi/ProductApiDetail.tsx
  src/features/productId/components/ProductApi/ProductYouTubeSection.tsx
  src/features/productId/hooks/YoutubeVideo.ts
  src/features/productId/libs/mongo.ts
Labels: ✨ feature

#146 [Refactor/ksy/code clean] - 코드 리펙토링 기능 바뀐거 없음
  src/app/api/spotify-token/route.ts
  src/app/product/[id]/page.tsx
  src/app/signin/error.tsx
  src/app/signup/useSignUp.ts
  src/features/productId/axiosInstance.ts
  src/features/productId/components/ProductApi/ProductApiClient.tsx
  src/features/productId/components/ProductApi/ProductApiDetail.tsx
  src/features/productId/components/ProductApi/ProductSpotifyClient.tsx
  src/features/productId/components/ProductApi/ProductYouTubeSection.tsx
  src/features/productId/components/ProductIdDetail/CopyLinkImage.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetail.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetailButton.tsx
  src/features/productId/components/ProductIdDetail/ProductIdDetailHeart.tsx
  src/features/productId/components/ProductIdStats/ProductIdStats.tsx
  src/features/productId/components/ProductIdStats/ProductIdStatsClient.tsx
  src/features/productId/components/ProductReviews/ProductReviewsInfinite.tsx
  src/features/productId/components/modal/ProductCompareModal/ProductCompareModal.tsx
  src/features/productId/components/modal/ProductReviewModal/ProductReviewInputModal.tsx
  src/features/productId/components/modal/ProductReviewModal/ReviewBaseModal.tsx
  src/features/productId/hooks/useDeleteModal.ts
  src/features/productId/hooks/useGetProductSort.ts
  src/features/productId/hooks/useGetProductsIdReviews.ts
  src/features/productId/libs/getProductReviewsKey.ts
  src/features/productId/libs/productStore.ts
  src/features/signup/components/SignUpPage.tsx
  test/test.http
Labels: ♻️ refactor
